---
openapi: "3.0.0"
info:
  title: "Flight Blender API specification"
  description: "All APIs for Flight Blender"
  version: "1.0.0"
servers:
- url: "https://virtserver.swaggerhub.com/cygnus2936/flight-blender/1.0.0"
  description: "Flight Blender API Specification"
security:
- flight_blender_service:
  - "write"
  
paths:
  /set_air_traffic:
    post:
      summary: "Add Airtraffic observation into Flight Blender"
      description: "Submit air traffic data to the service to normalize\
        \ which normalizes the data and eventually sends it to Flight Spotlight. A single or multiple observation must be submitted"

      requestBody:
        required: true
        content:
          application/json:
            schema:
              Observations:
                type: object
                observations: 
                  $ref: '#/definitions/ArrayOfObservations'

      responses:
        "200":
          description: "OK"
        "401":
          description: Not authenticated
        "403":
          description: Access token does not have the required scope
 
        
components:
  schemas: {}
  securitySchemes:
    flight_blender_service:
      type: "oauth2"
      flows:
        clientCredentials:
          tokenUrl: "http://id.openskies.sh/oauth/token"
          scopes:
            write: "Write data into Flight Blender"

definitions:
  ArrayOfObservations:     
    type: array
    items:
      type: object
      required:
        - lon_dd
        - lat_dd
        - timestamp
        - altitude_mm
        - icao_address
      
      properties:
        lon_dd:
          type: number     
          format: float
        lat_dd:
          type: number  
          format: float
        timestamp:
          type: integer      
          format: int64
        icao_address:
          type: string
          maxLength: 24
        source_type:
            type: integer
        traffic_source:
            type: integer
            