---
openapi: "3.0.0"
info:
  title: "Flight Blender API specification"
  description: "All APIs for Flight Blender"
  version: "1.0.0"
servers:
- url: "https://virtserver.swaggerhub.com/cygnus2936/flight-blender/1.0.0"
  description: "Flight Blender API Specification"
security:
- flight_blender_service:
  - "write"
  
paths:
  /set_air_traffic:
    post:
      summary: "Set Airtraffic data"
      description: "Submit air traffic data to the service to normalize\
        \ and submit eventually to Flight Spotlight."
      parameters:
        - in: body
          name: observations
          description: A single or multiple air-traffic obervation per the Airtraffic data protocol.
          schema:
            $ref: '#/definitions/AirTraffic'
      responses:
        "200":
          description: "OK"
        "401":
          description: Not authenticated
        "403":
          description: Access token does not have the required scope
 
          

components:
  schemas: {}
  securitySchemes:
    flight_blender_service:
      type: "oauth2"
      flows:
        clientCredentials:
          tokenUrl: "http://id.openskies.sh/oauth/token"
          scopes:
            write: "Write data into Flight Blender"

definitions:
  AirTraffic:     
    type: object
    required:
      - lon_dd
      - lat_dd
      - timestamp
      - altitude_mm
      - icao_address
    
    properties:
      lon_dd:
        type: number     
        format: float
      lat_dd:
        type: number  
        format: float
      timestamp:
        type: integer      
        format: int64
      icao_address:
        type: string
        maxLength: 24
      source_type:
          type: integer
      traffic_source:
          type: integer